#!/bin/bash

svn checkout -r 33991 https://svn.rosettacommons.org/source/trunk/rosetta/rosetta_source
svn checkout -r 33991 https://svn.rosettacommons.org/source/trunk/rosetta/rosetta_database
cd rosetta_source
./scons.py bin mode=release extras=static
