#!/bin/bash

svn checkout -r 32231 https://svn.rosettacommons.org/source/trunk/rosetta/rosetta_source
svn checkout -r 32257 https://svn.rosettacommons.org/source/trunk/rosetta/rosetta_database
cp pilot_apps.src.settings.my rosetta_source/src/
cp devel.src.settings.my rosetta_source/src/
cd rosetta_source
./scons.py bin mode=release extras=static
./scons.py bin mode=release extras=static my_pilot_apps
cp bin/fix_bb_monomer_ddg.linuxgccrelease ..
